### ISSUE TITLE
is-valid tools return zero on some types of failure

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fms_yaml_tools#61]
On parsing errors they return 1 as expected.

But on other errors they return 0. e.g.

```
data_table:
- grid_namename: LND
  fieldname_in_model: phot_co2
  factor:
  override:
  - file_name: INPUT/co2_data.nc
    fieldname_in_file: co2
    interp_method: bilinear
```

```
is-valid-data-table-yaml data-bad.yaml

The following errors have occurred:

(1) None is not of type 'number'---deque(['data_table', 0, 'factor'])
(2) 'grid_name' is a required property---deque(['data_table', 0])
(3) Additional properties are not allowed ('override', 'grid_namename' were unexpected)---deque(['data_table', 0])

gaea58:~/fre-commands%>echo $status 
0
```
