### ISSUE TITLE
Reason for error message: "diag_manager_mod: You skipped a time_step."

### ISSUE THREAD

**Issue by matt-morin** [NOAA-GFDL/fms_yaml_tools#71]
I have recently started work switching from the legacy to the yaml diag_table for use with the 2025 real-time C-SHiELD model.
When I run the model with the yaml diag_table enabled (details below), the model crashes with the error message:
**- FATAL from PE     0: atmos_phys_1h: diag_manager_mod: You skipped a time_step. Be sure that diag_send_complete is called at every time_step needed by the file.**

Here are the steps I have taken:
- confirmed that FMS was compiled with "-Duse_yaml"
- added "use_modern_diag = .true." to diag_manager_nml
- changed all references of "diag_table" to "diag_table.yaml"
- converted my legacy diag_table to yaml using diag-table-to-yaml

For my initial testing, I am using a simplified/reduced diag_table. Here it is:
```
title: 20250506.00Z.C768n5r10_hwt.RT2025_yaml
base_date: 2025 5 6 0 0 0
diag_files:
- file_name: atmos_phys_1h
  time_units: hours
  unlimdim: time
  freq: 1 hours
  varlist:
  - module: gfs_phys
    var_name: totprcpb_ave
    output_name: PRATEsfc
    reduction: none
    kind: r4
  - module: gfs_phys
    var_name: DSWRFsfc
    reduction: none
    kind: r4
  - module: gfs_phys
    var_name: USWRFsfc
    reduction: none
    kind: r4
```

My test forecast run is set to only 6 hours. Here are some other relevant settings:
```
set fdiag = "1."
set fhzer = "1."
set fhcyc = "24."
set first_time_step = ".false."
```

At the end of this test run the following history files are produced:
```
atmos_phys_1h.nest02.tile7.nc
atmos_phys_1h.tile1.nc
atmos_phys_1h.tile2.nc
atmos_phys_1h.tile3.nc
atmos_phys_1h.tile4.nc
atmos_phys_1h.tile5.nc
atmos_phys_1h.tile6.nc
```
However, these files do not appear to contain any model output data:
```
% ncdump -v time atmos_phys_1h.tile1.nc
netcdf atmos_phys_1h.tile1 {
dimensions:
        grid_xt = 768 ;
        grid_yt = 768 ;
        time = UNLIMITED ; // (0 currently)
variables:
        float grid_xt(grid_xt) ;
                grid_xt:long_name = "T-cell longitude" ;
                grid_xt:axis = "X" ;
                grid_xt:units = "degrees_E" ;
        float grid_yt(grid_yt) ;
                grid_yt:long_name = "T-cell latitude" ;
                grid_yt:axis = "Y" ;
                grid_yt:units = "degrees_N" ;
        double time(time) ;
                time:long_name = "time" ;
                time:units = "hours since 2025-05-06 00:00:00" ;
                time:axis = "T" ;
                time:calendar_type = "JULIAN" ;
                time:calendar = "julian" ;
        float USWRFsfc(time, grid_yt, grid_xt) ;
                USWRFsfc:long_name = "Interval-averaged unadjusted upward shortwave flux at the surface" ;
                USWRFsfc:units = "W/m**2" ;
                USWRFsfc:missing_value = 9.99e+20f ;
                USWRFsfc:_FillValue = 9.99e+20f ;
                USWRFsfc:cell_methods = "time: point" ;
```

What is the likely cause of this error from diag_manager_mod?

Many thanks!
-Matt
